### ISSUE TITLE
Remove root user in the action's Dockerfile

### ISSUE THREAD

**Issue by avinashupadhya99** [kubescape/github-action#1]
The action is currently running as a `root` user. This is not ideal due to security implications.

The user should not be a root user.

> P.S.: Thoroughly test the action before making a PR.

**Comment by shiwwamm** [comment]
I want to work on this issue, I know about users in containers and the UIDs.

**Comment by Tushar255** [comment]
I want to work on this issue, I'm a beginner and want to learn things by doing.

**Comment by FavourDaniel** [comment]
If this hasn't been assigned to anyone I would love to work on it.

**Comment by avinashupadhya99** [comment]
Closed through #3
