### ISSUE TITLE
 request for creating a Kubescape GitLab job

### ISSUE THREAD

**Issue by akkie70** [kubescape/github-action#12]
I was trying to run Kubescape in Gitlab cicd and followed the instructions https://hub.armosec.io/docs/gitlab but failed. Can we create Gitlab actions so we can use it in a pipline for scanning and possible send out scan results with mail?
![unknown](https://user-images.githubusercontent.com/114095478/191682491-9768b14f-14c8-49fd-80b4-a4146194911a.png)

**Comment by Atharva-Shinde** [comment]
hey @dwertent can you assign me this issue, I would like to work on this one

**Comment by craigbox** [comment]
Addressed in the linked bug.
