### ISSUE TITLE
[Feature] Add support for repository scanning

### ISSUE THREAD

**Issue by avinashupadhya99** [kubescape/github-action#2]
Kubescape supports scanning entire repositories - https://hub.armosec.io/docs/repository-scanning

The GitHub action should support an option for scanning the entire repository.

- The feature should be through a mandatory input - `scanRepository`, which should accept `yes` or `no`.
- If the input is set to `yes`, the value for the `accountGUID` needs to be provided as an input. The input `accountGUID` should be an optional input and validated only if the input `scanRepository` is set to yes.
- If the input `scanRepository` is not set to yes, the current functionality of the action should be performed. If not, the [repository scan](https://hub.armosec.io/docs/repository-scanning) should be performed and the results should be sent to the SaaS platform.
- The updates should be documented in the README with examples.

Reach out in the [Kubescape Discord Server](https://discord.com/invite/WKZRaCtBxN) in the `github-action-development` channel or leave a comment on this issue for details/help/interest.

**Comment by SD-13** [comment]
Hey @avinashupadhya99 , Can I work on this issue?

**Comment by avinashupadhya99** [comment]
Sure, go ahead.

**Comment by shiwwamm** [comment]
I want to work on this issue.

**Comment by shiwwamm** [comment]
The goal here is to scan the repository in which the action is called, or do we have to take a repository link as input?

**Comment by shiwwamm** [comment]
> The goal here is to scan the repository in which the action is called, or do we have to take a repository link as input?

As mentioned in the discord channel, what we want is to set up the github action in a repo and make it fulfill the two goals as specified.
We only want to scan the repo in which action is specified, there's no reason to scan another repository.

**Comment by dwertent** [comment]
PR #9
