### ISSUE TITLE
[Enhancement] Add parameter for exceptions

### ISSUE THREAD

**Issue by avinashupadhya99** [kubescape/github-action#4]
Currently, [exceptions](https://hub.armosec.io/docs/exceptions) are supported as `args`. It needs to be a separate parameter since it plays a central role for the user.

- [ ] Create parameter for `exceptions` and set it to optional
- [ ] Update docs with example and remove `exceptions` from the `args` list in the docs
- [ ] The exceptions provided through the parameter should be placed after the flags passed through args during the execution in the [script](https://github.com/kubescape/github-action/blob/abf1f175442f783fd13a4a8bd1c651a568eddb33/entrypoint.sh#L27).

**Comment by MukulKolpe** [comment]
Hey @avinashupadhya99, can I work on this issue?

**Comment by TheSuperSid777** [comment]
Hey @avinashupadhya99, can I also work on this issue?

**Comment by avinashupadhya99** [comment]
@MukulKolpe Go ahead. Reach out either here or on the discord if you have any queries. Make sure to keep us posted with your progress.

@TheSuperSid777 Sorry, please feel free to choose another issue from the Kubescape organization

**Comment by shiwwamm** [comment]
@MukulKolpe Are you working on this issue? Can you update us about your progress?
If you haven't worked on the issue, then I would like to make a pr as I have solved the issue.
I still have to add examples to docs, Maybe we can collaborate on that.

**Comment by MukulKolpe** [comment]
@orrgato since you have already solved the issue, feel free to make a PR. Sure we can collaborate on adding examples for the same in the docs.

**Comment by avinashupadhya99** [comment]
Closed via #5
